#!/bin/bash

if [[ "$LEGACY" == "true" ]]; then
APP_PATH="/app/btsync-1.4" 
CONF_PATH="/config/legacy-btsync.conf"
else
APP_PATH="/app/btsync-latest" 
CONF_PATH="/config/latest-btsync.conf"
fi

exec /sbin/setuser abc "$APP_PATH"/btsync  --config "$CONF_PATH" --nodaemon
